// <auto-generated />
using System;
using AssiDay02MVC.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssiDay02MVC.Data.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    partial class CompanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssiDay02MVC.Models.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Degree")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("MinDegree")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100m,
                            DepartmentId = 1,
                            MinDegree = 50m,
                            Name = "Database"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100m,
                            DepartmentId = 1,
                            MinDegree = 50m,
                            Name = "Algorithms"
                        });
                });

            modelBuilder.Entity("AssiDay02MVC.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MgrName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MgrName = "Mohamed",
                            Name = "CS"
                        },
                        new
                        {
                            Id = 2,
                            MgrName = "Nagy",
                            Name = "IS"
                        });
                });

            modelBuilder.Entity("AssiDay02MVC.Models.StuCrsRes", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StuCrs");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1,
                            Grade = 85m
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 1,
                            Grade = 90m
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 2,
                            Grade = 78m
                        });
                });

            modelBuilder.Entity("AssiDay02MVC.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            DepartmentId = 1,
                            Name = "Ali"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            DepartmentId = 1,
                            Name = "Omar"
                        },
                        new
                        {
                            Id = 3,
                            Age = 20,
                            DepartmentId = 2,
                            Name = "Mostafa"
                        });
                });

            modelBuilder.Entity("AssiDay02MVC.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            CourseId = 1,
                            DepartmentId = 1,
                            Name = "Mohamed",
                            Salary = 8000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            CourseId = 2,
                            DepartmentId = 1,
                            Name = "Nagy",
                            Salary = 7500m
                        });
                });

            modelBuilder.Entity("AssiDay02MVC.Models.Courses", b =>
                {
                    b.HasOne("AssiDay02MVC.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AssiDay02MVC.Models.StuCrsRes", b =>
                {
                    b.HasOne("AssiDay02MVC.Models.Courses", "Course")
                        .WithMany("StuCrs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssiDay02MVC.Models.Student", "Student")
                        .WithMany("StuCrs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AssiDay02MVC.Models.Student", b =>
                {
                    b.HasOne("AssiDay02MVC.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AssiDay02MVC.Models.Teacher", b =>
                {
                    b.HasOne("AssiDay02MVC.Models.Courses", "Course")
                        .WithMany("Teachers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssiDay02MVC.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AssiDay02MVC.Models.Courses", b =>
                {
                    b.Navigation("StuCrs");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("AssiDay02MVC.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("AssiDay02MVC.Models.Student", b =>
                {
                    b.Navigation("StuCrs");
                });
#pragma warning restore 612, 618
        }
    }
}
